### ISSUE TITLE
SwiftESCL in NSViewController

### ISSUE THREAD

**Issue by pol2095** [LeoKlaus/SwiftESCL#5]
Hello,,

I need to use `SwiftESCL` in a `NSViewController` but it's impossible to use `@State` : 

```
import Cocoa
import Foundation
import SwiftESCL
import SwiftUI
import AppKit

class ViewController: NSViewController {

    @State var discoveredDevices: [String:ScannerRepresentation] = [:]
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        let button = NSButton(frame: NSRect(x: 150, y: 200, width: 80, height: 55))
        button.title =  "A button in code"
        self.view.addSubview(button)
        button.target = self
        button.action = #selector(buttonTest)
        
        let browser = Browser(usePlainText: true)
        // The string contains the hostname of the device, which should be sufficient to uniquely identify it.
        //@State var discoveredDevices: [String:SwiftESCL.ScannerRepresentation] = [:]
        // As the discovery runs asynchronously, it's easiest to just pass the dictionary as binding
        browser.setDevices(scanners: $discoveredDevices)
        // Now you just have to start the browser to discover devices:
        browser.start()

        // Do any additional setup after loading the view.
    }
    
    @objc func buttonTest() {
        print("Test button")
        print(discoveredDevices.count)
    }

    override var representedObject: Any? {
        didSet {
        // Update the view, if already loaded.
        }
    }
}
```

Thanks

**Comment by LeoKlaus** [comment]
I'm not very familiar with UIKit/AppKit, the given example is meant for SwiftUI.

I don't think the `@State` and `@Binding` wrappers exists in AppKit.

The browser is hardcoded to use a `@Binding` variable, so you'll either need to use `NSHostingView()` to present a SwiftUI view for the scanner items
``` swift
override func viewDidLoad() {
        super.viewDidLoad()
        ...
        let deviceView = NSHostingView(rootView: DiscoverDevices())
        self.view.addSubview(deviceView)
        ...
```
or fork and modify SwiftESCL (if you do that, I'd happily merge a PR).

If you need inspiration for how to use SwiftESCL in SwiftUI, you can check out [OpenAirScan](https://github.com/LeoKlaus/OpenAirScan). Feel free to use any of the views I've written there (though I recommend writing your own, these are some of the first SwiftUI views I've written).

Device discovery is handled here:
https://github.com/LeoKlaus/OpenAirScan/blob/main/OpenAirScan/Views/DiscoverDevices.swift

**Comment by pol2095** [comment]
I added a callback method instead of @State  for Storyboard app, for SwifUI app is better to use Binding,

**Comment by pol2095** [comment]
I have an other question :
`(imageData, self.responseCode) = scanner.scanDocument(resolution: 300, format: "image/jpeg", source: "Platen", width: 2480, height: 3508)`
I have a `responseCode` `503` and after `200`, what does it correspond to ?
Thanks

**Comment by LeoKlaus** [comment]
I suggest looking at the [ESCL spec](https://mopria.org/spec-download). 503 should indicate that the scanner is not ready to accept the job.

**Comment by pol2095** [comment]
Thanks a lot, how work `scanDocument()` using a feeder (multiple pages) ?

**Comment by LeoKlaus** [comment]
> `scanDocument()` using a feeder (multiple pages) ?

My printer handles the feeder as one document: One scanjob will lead to a multi-page PDF.

**Comment by LeoKlaus** [comment]
One thing I've learned is that not all printers strictly adhere to the spec. Especially Brother devices often don't work with my implementation.

**Comment by pol2095** [comment]
For "image/jpeg", what it return for multiple pages ?

**Comment by LeoKlaus** [comment]
I haven't tried that, but I'd suspect the scanner either scans just a single page or creates multiple jobs.

**Comment by pol2095** [comment]
I tried, the scanner return only one page and the task isn't finished, wait...

**Comment by pol2095** [comment]
In the ESCL spec.
`For all document formats that support multiple pages (PDF, TIFF etc.,), the scanner SHOULD upload a single file with all the scan pages merged together. For the document formats that do not support multiple pages (like JPEG), the clients SHOULD retrieve the individual JPEG scan images and can do any post-processing operation.`
```
After initiating the scan job, the client is responsible to pace the retrieval of the scan pages. In this document, this transactional model is labeled: Pull Scan.
Once the job is created, the scanner SHOULD be in Pending or Processing state. The client keeps checking the scanner status and the client uses the job URL to upload the next scan page after the JobState moves to Pending or Processing. The client keeps invoking this URL until the NextDocument request returns 404 Not Found. When all pages are scanned, the JobState MUST indicate ‘Completed’ denoting there are no more pages to be uploaded. The JobState SHOULD indicate ‘Canceled’ or ‘Aborted’ if the job was either canceled by the user or due to internal abort
If the NextDocument request times out, the client SHOULD check the JobState and retry pulling the scan pages if the JobState is either Pending or Processing.
After the job is created, if the client fails to retrieve the scan pages for some reason – could be even a network failure, the scanner MAY abort the scan job after a certain time period determined by the scanner. The scanner SHOULD NOT cancel the job if it can retain the scan pages for a longer period without resource constraints.
```

**Comment by pol2095** [comment]
I understanded how it work, I used `responseURL` to download the jpeg images
`let (responseURL, postResponseCode) = scanner.sendPostRequest(resolution: 300, format: "image/jpeg", source: "Adf", width: 2480, height: 3508)`
to get 4 pges, download a file using `responseURL` 4 times.

**Comment by pol2095** [comment]
Thanks for your help.
